# Client deployment
apiVersion: apps/v1
kind : Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: $APP_NAME.azurecr.io/client:$VERSION
        ports:
          - containerPort: 3000
      
---

# Service for the client deployment
apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  selector:
    app: client
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer
  
---

# Server deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: $APP_NAME.azurecr.io/server:$VERSION
        ports:
          - containerPort: 5001
        env:
          - name: mongo_url
            value: "mongodb+srv://shmp:shmp@cluster27.d6hauw2.mongodb.net/shmp?retryWrites=true&w=majority"
          - name: jwt_secret
            value: "shmp"
          - name: cloud_name
            value: "dejm9izfx"
          - name: cloud_api_key
            value: "555179651852497"
          - name: cloud_api_secret
            value: "BueLBWwGGQkuf6BjLM2n8v4pJRM"

---

# Service for the server deployment
apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  selector:
    app: server
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001
  type: ClusterIP