name: Deploy Prometheus and Grafana

on:
  workflow_dispatch:  # Run this workflow manually

jobs:
  deployMonitoring:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up Kubernetes credentials using KUBE_CONFIG secret
    - name: Configure kubectl with KUBE_CONFIG
      uses: azure/setup-kubectl@v3
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG }}  # Load KUBE_CONFIG from GitHub Secrets

    # Set up Helm for Prometheus and Grafana deployment
    - name: Set up Helm
      run: curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3

    # Add Prometheus and Grafana Helm repositories
    - name: Add Helm repositories
      run: |
        helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
        helm repo add grafana https://grafana.github.io/helm-charts
        helm repo update

    # Deploy Prometheus using Helm
    - name: Deploy Prometheus
      run: |
        helm upgrade --install prometheus prometheus-community/prometheus \
          --namespace monitoring \
          --create-namespace \
          --set alertmanager.persistentVolume.storageClass="default" \
          --set server.persistentVolume.storageClass="default"

    # Deploy Grafana using Helm
    - name: Deploy Grafana
      run: |
        helm upgrade --install grafana grafana/grafana \
          --namespace monitoring \
          --set persistence.enabled=true \
          --set persistence.storageClassName="default" \
          --set adminPassword='admin' \
          --set service.type=LoadBalancer