name: Deploy SonarQube

on:
  workflow_dispatch:  # Trigger the workflow manually

jobs:
  deploy_sonarqube:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up kubectl
      uses: tale/kubectl-action@v1
      with:
        base64-kube-config: ${{ secrets.KUBE_CONFIG }}
        kubectl-version: v1.24.2

    # Deploy SonarQube
    - name: Deploy SonarQube
      run: kubectl apply -f ./scripts/kubernetes/sonarqube-deployment.yaml

